task:
  timeout_in: 300m
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sequoia
    cpu: 8
    memory: 32G

  Pre-build_script:
    - brew update
    - brew upgrade
    - brew install bash curl gcc jq git wget
  
  Build_script:
    - git clone --depth=1 https://github.com/aldrin1127/kicad-mp-ng.git
    - cd kicad-mp-ng
