task:
  timeout_in: 300m
  container:
    image: archlinux:base-devel
    cpu: 8
    memory: 32G

  Pre-build_script:
    - pacman -Syyuu --noconfirm
    - pacman -Syyuu --noconfirm bash curl git sudo wget
    - useradd -s /bin/bash -m builder
    - echo 'builder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
    - |
      su - builder -c /bin/bash <<SCRIPT
      cd /home/builder
      git clone --depth=1 https://aur.archlinux.org/paru-git.git
      pushd paru-git
      makepkg -sic --noconfirm
      popd
      rm -rf paru-git
      paru -Syu jdk-temurin android-sdk-cmdline-tools-latest
      source /etc/profile
      sdkmanager --update
      yes | sdkmanager --licenses
      sdkmanager "platforms;android-35" "build-tools;35.0.0" "ndk-bundle"
      SCRIPT
  
  Build_script:
    - git clone --depth=1 https://github.com/aldrin1127/kicad-mp-ng.git
    - cd kicad-mp-ng
